# Generated by Django 5.0.1 on 2025-05-23 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("duration_minutes", models.IntegerField(db_index=True)),
                (
                    "price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
                ),
                ("is_online", models.BooleanField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weekday", models.IntegerField(db_index=True)),
                ("start_time", models.TimeField(db_index=True)),
                ("end_time", models.TimeField(db_index=True)),
                ("doctor_id", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="UsersMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient", "patient"),
                            ("doctor", "doctor"),
                            ("employee", "employee"),
                        ],
                        default="patient",
                        max_length=16,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("finished", "Finished"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=255,
                    ),
                ),
                ("patient_id", models.UUIDField()),
                ("doctor_id", models.UUIDField()),
                (
                    "appointment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visits.appointmenttype",
                    ),
                ),
            ],
        ),
    ]
