# Generated by Django 5.0.1 on 2025-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0002_appointment_zoom_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersmapping",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "patient"),
                    ("doctor", "doctor"),
                    ("employee", "employee"),
                    ("admin", "admin"),
                ],
                default="patient",
                max_length=16,
            ),
        ),
    ]
