# Generated by Django 5.2 on 2025-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0003_alter_usersmapping_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorschedule",
            name="weekday",
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="doctorschedule",
            unique_together={("weekday", "id")},
        ),
    ]
