# Generated by Django 5.2 on 2025-06-01 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0004_alter_doctorschedule_weekday_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForbiddenUUID",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="usersmapping",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
