# Generated by Django 5.0.1 on 2025-06-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0005_forbiddenuuid_alter_usersmapping_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersmapping",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
