services:
  kong:
    build: ./kong
    container_name: kong
    restart: unless-stopped
    ports:
      - "8000:8000"    # Proxy
      - "8443:8443"    # Proxy (SSL)
      - "8001:8001"    # Admin
      - "8002:8002"    # GUI
      - "8444:8444"    # Admin (SSL)
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    networks:
      - iot
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment: 
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_PROCESS_ROLES=broker,controller 
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092,CONTROLLER://kafka:29093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT 
      - KAFKA_BROKER_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NODE_ID=1
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL  
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - iot
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - iot
  appointments-db:
    image: postgres:16-alpine
    container_name: appointments-db
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: appointments_db
      POSTGRES_USER: appointments_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data_appointments:/var/lib/postgresql/data
    networks:
      - iot
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "appointments_user", "-d", "appointments_db" ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: -p 5433

  appointments-service:
    build: ./appointments/
    container_name: appointments
    ports:
      - "8081:8081"
    environment:
      - KAFKA_BROKER=kafka:29092
      - NEW_APPOINTMENT_TOPIC=${NEW_APPOINTMENT_TOPIC}
      - APPOINTMENT_CANCELED_TOPIC=${APPOINTMENT_CANCELED_TOPIC}
    depends_on:
      - appointments-db
      - kafka
      - kong
    networks:
      - iot
    
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db    
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    networks:
      - iot
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "auth_user", "-d", "auth_db"]
      interval: 30s
      timeout: 10s
      retries: 3
  auth-service:
    build: ./auth/
    container_name: auth
    ports:
      - "8082:8082"
    environment:
      - KAFKA_BROKER=kafka:29092
      - JWT_SECRET="TOO MANY SECRETS"
      - USER_REGISTER_TOPC=${REGISTER_RESPONSE_TOPIC}
      - PATIENT_REGISTERED_TOPIC=${PATIENT_REGISTERED_TOPIC}
      - EMPLOYEE_HIRED_TOPIC=${EMPLOYEE_HIRED_TOPIC}
      - PASSWORD_CHANGED_TOPIC=${PASSWORD_CHANGED_TOPIC}
      - USER_CREATION_FAILED_TOPIC=${USER_CREATION_FAILED_TOPIC}
      - IDENTITY_CONFIRMED_TOPIC=${IDENTITY_CONFIRMED_TOPIC}
    depends_on:
      - auth-db
      - kafka
    networks:
      - iot
  payment-gateway:
    build: ./payment_gateway/
    container_name: payu
    environment:
      - KAFKA_BROKER=kafka:29092
      - client_id=${PAYU_CLIENT_ID}
      - client_secret=${PAYU_CLIENT_SECRET}
      - PAYMENT_CREATED_TOPIC=${PAYMENT_CREATED_TOPIC}
      - REFUND_REQUESTED_TOPIC=${REFUND_REQUESTED_TOPIC}
      - REFUND_ERROR_TOPIC=${REFUND_ERROR_TOPIC}
      - REFUND_CREATED_TOPIC=${REFUND_CREATED_TOPIC}
    depends_on:
      - kafka
    networks:
      - iot
  payment-service:
    build: ./payment_service
    container_name: payment-service
    ports:
      - "8088:8088"
    depends_on:
      - mongodb
      - kafka
    environment:
      - NEW_APPOINTMENT_TOPIC=${NEW_APPOINTMENT_TOPIC}
      - APPOINTMENT_CANCELED_TOPIC=${APPOINTMENT_CANCELED_TOPIC}
      - MONGO_URI=mongodb://mongodb:27017
      - KAFKA_BROKER=kafka:29092
      - PAYMENT_CREATED_TOPIC=${PAYMENT_CREATED_TOPIC}
      - REFUND_ERROR_TOPIC=${REFUND_ERROR_TOPIC}
      - REFUND_REQUESTED_TOPIC=${REFUND_REQUESTED_TOPIC}
      - REFUND_CREATED_TOPIC=${REFUND_CREATED_TOPIC}
    networks:
      - iot
  email-service:
    build: ./email_service/EmailService/
    container_name: email_service
    ports:
      - "6764:8080"
    environment:
      - Kafka__ServerAddress=kafka:29092
      - Kafka__UserRegistredTopic=${REGISTER_RESPONSE_TOPIC}
      - Kafka__AppointmentCreatedTopic=${NEW_APPOINTMENT_TOPIC}
      - Kafka__ChangePasswordTopic=${PASSWORD_CHANGED_TOPIC}
      - Kafka__AppointmentCancelledTopic=${APPOINTMENT_CANCELED_TOPIC}
      - Kafka__ZoomCreatedTopic=${ZOOM_CREATED_TOPIC}
      - SMTP__ServerAddress=smtp.gmail.com
      - SMTP__Email=${SMTP_EMAIL}
      - SMTP__From=AngioCard
      - SMTP__Password=${SMTP_PASSWORD}
      - SMTP__PORT=587
      - Database__ConnectionString=mongodb://mongodb:27017
      - Database__DatabaseName=database
    volumes:
      - ./email_service/EmailService/Templates:/app/Templates
    depends_on:
      - kafka
    networks:
      - iot     
  document-service:
    build: ./document_service/DocumentService/
    container_name: document_service
    ports:
      - "6868:8080"
    environment:
      - ConnectionStrings__DataConnection=Host=patient-db;Port=5434;Username=patient_user;Password=secret;Database=patientdb
      - Storage__BucketName=${BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=us-east-1
    depends_on:
      - patient-db
    networks:
      - iot     
  patient-db:
    image: postgres:16-alpine
    container_name: patient-db
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: patient_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data_patient:/var/lib/postgresql/data
    networks:
      - iot
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "patient_user", "-d", "patientdb"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: -p 5434

  patient-register-service:
    build: ./patient_register_service/PatientRegisterService/
    container_name: patient_register_service
    ports:
      - "9606:8080"
    environment:
      - Kafka__ServerAddress=kafka:29092
      - Kafka__PatientRegisterTopic=${PATIENT_REGISTER_TOPIC}
    depends_on:
      - kafka
    networks:
      - iot     
  patient-service:
    build: ./patient_service/PatientService/
    container_name: patient
    ports:
      - "9696:8080"
    environment:
      - Kafka__ServerAddress=kafka:29092
      - Kafka__UserCreationFailedTopic=${USER_CREATION_FAILED_TOPIC}
      - Kafka__PatientRegisterTopic=${PATIENT_REGISTER_TOPIC}
      - Kafka__PatientRegisteredTopic=${PATIENT_REGISTERED_TOPIC}
      - Kafka__IdentityConfirmedTopic=${IDENTITY_CONFIRMED_TOPIC}
      - ConnectionStrings__DataConnection=Host=patient-db;Port=5434;Username=patient_user;Password=secret;Database=patientdb
    depends_on:
      - kafka
      - patient-db
    networks:
      - iot
  employee-service:
    build: ./employee_service/EmployeeService/
    container_name: employee
    ports:
      - "9666:8080"
    environment:
      - Kafka__ServerAddress=kafka:29092
      - Kafka__EmployeeHiredTopic=${EMPLOYEE_HIRED_TOPIC}
      - Kafka__EmployeeRegistrationFailedTopic=${USER_CREATION_FAILED_TOPIC}
      - Kafka__EmployeeDismissedTopic=${EMPLOYEE_FIRED_TOPIC}
      - ConnectionStrings__DataConnection=Host=patient-db;Port=5434;Username=patient_user;Password=secret;Database=patientdb
    depends_on:
      - kafka
      - patient-db
    networks:
      - iot
  zoom-handler:
    build: ./zoom/
    container_name: zoom-handler
    environment:
      - KAFKA_BROKER=kafka:29092
      - NEW_APPOINTMENT_TOPIC=${NEW_APPOINTMENT_TOPIC}
      - ZOOM_CREATED_TOPIC=${ZOOM_CREATED_TOPIC}
      - ZOOM_ACCOUNT_ID=${ZOOM_ACCOUNT_ID}
      - ZOOM_CLIENT_ID=${ZOOM_CLIENT_ID}
      - ZOOM_CLIENT_SECRET=${ZOOM_CLIENT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    depends_on:
      - kafka
      - kong
      - appointments-service
    networks:
      - iot

networks:
  iot:
    driver: bridge

volumes:
  postgres_data_auth:
  postgres_data_patient:
  postgres_data_appointments:
  mongo_data: