services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment: 
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_PROCESS_ROLES=broker,controller 
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092,CONTROLLER://kafka:29093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT 
      - KAFKA_BROKER_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL  
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - iot
  api-gateway:
    build: ./api_gateway/
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKER=kafka:29092
      - REQUEST_TOPIC_PAYMENT=${REQUEST_TOPIC_PAYMENT}
      - RESPONSE_TOPIC_ORDERS=${RESPONSE_TOPIC_ORDERS}
    depends_on:
      - kafka
    networks:
      - iot
  email-service:
    build: .\email_service\EmailService\
    ports:
      - "6764:8080"
    environment:
      - Kafka__ServerAddress=kafka:29092
      - Kafka__UserRegistredTopic=${REGISTER_RESPONSE_TOPIC}
      - SMTP__ServerAddress=smtp.gmail.com
      - SMTP__Email=${SMTP_EMAIL}
      - SMTP__From=AngioCard
      - SMTP__Password=${SMTP_PASSWORD}
      - SMTP__PORT=587
    volumes:
      - ./email_service/EmailService/Templates:/app/Templates
    depends_on:
      - kafka
    networks:
      - iot     
  payment-gateway:
    build: ./payment_gateway/
    environment:
      - KAFKA_BROKER=kafka:29092
      - client_id=${client_id}
      - client_secret=${client_secret}
      - REQUEST_TOPIC_PAYMENT=${REQUEST_TOPIC_PAYMENT}
      - RESPONSE_TOPIC_ORDERS=${RESPONSE_TOPIC_ORDERS}
    depends_on:
      - kafka
    networks:
      - iot

networks:
  iot:
    driver: bridge
