version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=auth_db
      - DATABASE_USER=auth_user
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
