# Generated by Django 5.0.1 on 2025-05-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "patient"),
                    ("doctor", "doctor"),
                    ("employee", "employee"),
                    ("admin", "admin"),
                ],
                default="patient",
                max_length=16,
            ),
        ),
    ]
