# Generated by Django 5.2 on 2025-05-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.UUIDField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="identity_confirmed",
            field=models.BooleanField(default=True),
        ),
    ]
