// <auto-generated />
using System;
using EmployeeService.Infrastracture.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeService.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20250502004702_ChangeSchemaName")]
    partial class ChangeSchemaName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("employee")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeService.Domain.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("integer")
                        .HasColumnName("room_number");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.HasKey("Id")
                        .HasName("pk_doctor");

                    b.ToTable("doctor", "employee");
                });

            modelBuilder.Entity("EmployeeService.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsFired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fired");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<TimeOnly>("ShiftEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("shift_end_time");

                    b.Property<TimeOnly>("ShiftStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("shift_start_time");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.ToTable("employee", "employee");
                });

            modelBuilder.Entity("EmployeeService.Domain.Employee", b =>
                {
                    b.HasOne("EmployeeService.Domain.Doctor", "Doctor")
                        .WithOne("Employee")
                        .HasForeignKey("EmployeeService.Domain.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_doctor_id");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("EmployeeService.Domain.Doctor", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
